export const PAGE_TITLES = {
  dashboard:        'Dashboard',
  students:         'Sarthi Students',
  faculty:          'Sarthi Faculty',
  courses:          'Sarthi Courses',
  qb:               'Question Bank',
  syllabus:         'Syllabus Engine',
  evaluation:       'AI Evaluation',
  lms:              'Sarthi Hub',
  counselling:      'Career Counsellor',
  data:             'Data Management',
  notifications:    'Notifications',
  student_portal:   'My Portal',
  moderation_admin: 'Moderation',
  moderation:       'My Assignments',
  feedback:         'Feedback Board',
  ai_tutor:         'AI Tutor',
};

export const PAGE_SUBTITLES = {
  dashboard:        'Your Sarthi Platform',
  students:         'Manage enrolled students',
  faculty:          'Teaching staff directory',
  courses:          'Course catalog',
  qb:               'Practice question repository',
  syllabus:         'AI-powered syllabus understanding',
  evaluation:       'AI answer sheet grading',
  lms:              'Full LMS with AI evaluation',
  counselling:      'Sarthi Career Guidance',
  data:             'Import, export & manage university data',
  notifications:    'Stay up to date',
  student_portal:   'Your profile, grades & courses',
  moderation_admin: 'Paper review & moderation',
  moderation:       'Your assigned papers',
  feedback:         'Submit feedback, complaints & suggestions',
  ai_tutor:         'Course-specific AI powered by Ollama + Qwen2.5',
};
